// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfK66MuF_aYXW6Sec5oAl154eD2HvGVhs',
    appId: '1:964249519406:web:f8a59d805cd17c144ce6bf',
    messagingSenderId: '964249519406',
    projectId: 'doc-appointment-bb23b',
    authDomain: 'doc-appointment-bb23b.firebaseapp.com',
    storageBucket: 'doc-appointment-bb23b.appspot.com',
    measurementId: 'G-RZQPKWRL9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5B_4RFDgg9i2j0eWBfenmkN27HqquUoY',
    appId: '1:964249519406:android:fcc67c205ce96d9c4ce6bf',
    messagingSenderId: '964249519406',
    projectId: 'doc-appointment-bb23b',
    storageBucket: 'doc-appointment-bb23b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDexS7dZQPbCV7xTTAKBDEwJHoQvv_q7GY',
    appId: '1:964249519406:ios:1c75d94e4eb467aa4ce6bf',
    messagingSenderId: '964249519406',
    projectId: 'doc-appointment-bb23b',
    storageBucket: 'doc-appointment-bb23b.appspot.com',
    androidClientId: '964249519406-3o9dfbi1of77jhvpaokj3n2r2k2fkh07.apps.googleusercontent.com',
    iosClientId: '964249519406-4fr9d8svcnkqhhk8tho53okdpj7h4tkv.apps.googleusercontent.com',
    iosBundleId: 'com.majumder.pharmacy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDexS7dZQPbCV7xTTAKBDEwJHoQvv_q7GY',
    appId: '1:964249519406:ios:1c75d94e4eb467aa4ce6bf',
    messagingSenderId: '964249519406',
    projectId: 'doc-appointment-bb23b',
    storageBucket: 'doc-appointment-bb23b.appspot.com',
    androidClientId: '964249519406-3o9dfbi1of77jhvpaokj3n2r2k2fkh07.apps.googleusercontent.com',
    iosClientId: '964249519406-4fr9d8svcnkqhhk8tho53okdpj7h4tkv.apps.googleusercontent.com',
    iosBundleId: 'com.majumder.pharmacy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfK66MuF_aYXW6Sec5oAl154eD2HvGVhs',
    appId: '1:964249519406:web:a48204f1495fae724ce6bf',
    messagingSenderId: '964249519406',
    projectId: 'doc-appointment-bb23b',
    authDomain: 'doc-appointment-bb23b.firebaseapp.com',
    storageBucket: 'doc-appointment-bb23b.appspot.com',
    measurementId: 'G-PDFGXBQJHW',
  );

}