// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHcV5fBFUXyF-Fp2tM3R3S1EgFGfYbG8c',
    appId: '1:268434144883:web:3763f6c4fd286d60583406',
    messagingSenderId: '268434144883',
    projectId: 'majumder-pharmacy-bfda2',
    authDomain: 'majumder-pharmacy-bfda2.firebaseapp.com',
    storageBucket: 'majumder-pharmacy-bfda2.appspot.com',
    measurementId: 'G-3N6HP1EVFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLBDO8OImCj4wZRRwyoiF9VYqtaKTFpTY',
    appId: '1:268434144883:android:1dff68171c61b7d7583406',
    messagingSenderId: '268434144883',
    projectId: 'majumder-pharmacy-bfda2',
    storageBucket: 'majumder-pharmacy-bfda2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYQFCHYuUiDDfdaBCw5Sb5b8yqYvVJrcY',
    appId: '1:268434144883:ios:03c85349399134ed583406',
    messagingSenderId: '268434144883',
    projectId: 'majumder-pharmacy-bfda2',
    storageBucket: 'majumder-pharmacy-bfda2.appspot.com',
    iosBundleId: 'com.majumder.pharmacy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYQFCHYuUiDDfdaBCw5Sb5b8yqYvVJrcY',
    appId: '1:268434144883:ios:03c85349399134ed583406',
    messagingSenderId: '268434144883',
    projectId: 'majumder-pharmacy-bfda2',
    storageBucket: 'majumder-pharmacy-bfda2.appspot.com',
    iosBundleId: 'com.majumder.pharmacy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHcV5fBFUXyF-Fp2tM3R3S1EgFGfYbG8c',
    appId: '1:268434144883:web:a7d23de621c4f3a1583406',
    messagingSenderId: '268434144883',
    projectId: 'majumder-pharmacy-bfda2',
    authDomain: 'majumder-pharmacy-bfda2.firebaseapp.com',
    storageBucket: 'majumder-pharmacy-bfda2.appspot.com',
    measurementId: 'G-P3CCCSBH6Y',
  );

}